[package]
name = "openvcs-plugin-git"
version = "0.2.0"
edition = "2024"

[lib]
test = false
doctest = false

[features]
default = ["system-git"]
system-git = []
libgit2 = ["dep:git2", "dep:thiserror", "dep:time"]

[dependencies]
openvcs-core = { version = "0.1.8", features = ["plugin-protocol", "vcs"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
log = "0.4"
linkme = "0.3"

git2 = { version = "0.20", optional = true }
thiserror = { version = "2", optional = true }
time = { version = "0.3", features = ["parsing", "formatting"], optional = true }

[[bin]]
name = "openvcs-git-plugin"
path = "src/bin/openvcs-git-plugin.rs"
test = false
doctest = false
